### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by orschiro** [adelnizamutdinov/youtube-rss#18]
https://limitless-atoll-85321.herokuapp.com/channel/UC1Q831w4PGw2B-mKVTf7eAA

![screenshot from 2018-02-26 17-38-11](https://user-images.githubusercontent.com/170947/36682639-e2b2965e-1b1b-11e8-8f10-9bb7efda0281.png)

**Comment by adelnizamutdinov** [comment]
thanks, man

**Comment by adelnizamutdinov** [comment]
Ok, so I limited the feeds to be maximum 1400 items for now :)

need to research for further optimizations

**Comment by orschiro** [comment]
Glad I could help! :-)

**Comment by orschiro** [comment]
Hey @adelnizamutdinov,

Still broken for me. :-(

it's not rendering correctly. Anything we can do about it?

https://limitless-atoll-85321.herokuapp.com/user/GameStarDE

![image](https://user-images.githubusercontent.com/170947/36784023-3fd50868-1c7e-11e8-8183-aec222b77ded.png)

![image](https://user-images.githubusercontent.com/170947/36784040-520838ac-1c7e-11e8-89f6-f94ac8f62566.png)

![image](https://user-images.githubusercontent.com/170947/36784056-5dd7fbc2-1c7e-11e8-8631-a14e1470ab82.png)

**Comment by adelnizamutdinov** [comment]
yeah dude. Current implementation is too fragile. Let me think about it

**Comment by adelnizamutdinov** [comment]
this particular feed was fixed by limiting it to 1300 items

https://limitless-atoll-85321.herokuapp.com/user/GameStarDE

but I have a better solution in mind

**Comment by orschiro** [comment]
> but I have a better solution in mind

Which is what? :-)

**Comment by adelnizamutdinov** [comment]
I should implement proper [RFC 5005 paging](https://tools.ietf.org/html/rfc5005#section-3). I'm just kind of afraid that not a lot of players might support it. But I'll try and test

**Comment by adelnizamutdinov** [comment]
ok, so [Pocket Casts seem to be ignoring rss paging] paging(https://www.reddit.com/r/pocketcasts/comments/8153gt/are_atomlink_relnext_ignored/)

**Comment by orschiro** [comment]
How can I test if Player FM does the same?

**Comment by adelnizamutdinov** [comment]
I dunno, I'm trying to page through this 2500 item paged feed in Player FM, but I don't really understand it well, yet.

https://limitless-atoll-85321.herokuapp.com/playlist?list=PLv3TTBr1W_9tppikBxAE_G6qjWdBljBHJ

I don't even see the episode list

**Comment by orschiro** [comment]
Added this feed here: https://player.fm/series/instant-regret-clicking-this-playlist-memes

**Comment by adelnizamutdinov** [comment]
yeah, for some reason:

![image](https://user-images.githubusercontent.com/1594148/36846448-c1a24e62-1d6b-11e8-9fb2-e65c57475fa6.png)

**Comment by orschiro** [comment]
It may take a few minutes/hours to display. 

Let's monitor.

**Comment by adelnizamutdinov** [comment]
it seems that neither pocket casts nor player fm support podcast paging.
[Podcast Addict](https://play.google.com/store/apps/details?id=com.bambuna.podcastaddict&hl=en) does, but for some reason does not fetch all the pages and stops mid-way =/

**Comment by adelnizamutdinov** [comment]
Ok so improved the stability by further limiting the item limit to 1150.
Should fix the problem with application errors on concurrent requests.
Maybe I'll bring back RSS paging sometime down the road, but the lack of decent support from players makes the solution pretty futile

**Comment by adelnizamutdinov** [comment]
lol. 1400 -> 1300 -> 1150 item limit

pretty sad

**Comment by orschiro** [comment]
Still getting an application error on this one:

https://limitless-atoll-85321.herokuapp.com/user/GameStarDE

**Comment by adelnizamutdinov** [comment]
limited to 1000 items

hope it gets fixed

**Comment by orschiro** [comment]
See this post: https://plus.google.com/u/1/+RobertOrzanna/posts/6zkpteT255i

> Hi, I've updated it now. Their feed at https://limitless-atoll-85321.herokuapp.com/user/GameStarDE is extremely slow though. If you know them, you could suggest putting it behind a CDN like CloudFlare.

**Comment by ma7moudk** [comment]
The same issue happens now. 
Just reporting & Thank you for this wonderful work .
